export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_ONE_FILM_SUCCESS = 'FETCH_ONE_FILM_SUCCESS';
export const SHOW_ONE_FILM = 'SHOW_ONE_FILM';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';

export const ADD_NEW_FILM = 'ADD_NEW FILM';

export const FETCH_THIS_FILM_ORDER = 'FETCH_THIS_FILM_ORDER';


export const REMOVE_THIS_FILM_FROM_ORDER_LIST = 'REMOVE_THIS_FILM_FROM_ORDER_LIST';



export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';